name: Publish Artifacts

on:
  push:
    tags:
      - '*'

# Allow one concurrent deployment
concurrency:
  group: "deploy-maven"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -V -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn -V -B deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Build Artifacts
        run: |
          mkdir hugo-page-visits-fetcher ;
          cp target/hugo-page-visits-fetcher.jar hugo-page-visits-fetcher/hugo-page-visits-fetcher.jar ;
          cp -rf target/libs  hugo-page-visits-fetcher/libs ;
          tar -czf hugo-page-visits-fetcher.tag.gz hugo-page-visits-fetcher

      - name: Release Artifacts
        run: |
          hub release create --attach ./hugo-page-visits-fetcher.tag.gz --message "Release ${{github.ref_name}}" ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ github.token }}

